### ISSUE TITLE
需要手动创建实例目录

### ISSUE THREAD

**Issue by panpanxu** [francisar/rds_manager#1]
否则提示错误download error:  [Errno 2] No such file or directory: u'/data/rdsbackup/{instance_id}/hins482035_xtra_20151130042155.tar.gz'

**Comment by francisar** [comment]
恩恩，目前确实是需要先手工创建目录，在readme里有写，我稍后改下，改成检测目录是否存在，不存在先进行创建

**Comment by francisar** [comment]
增加了备份路径的判断和创建
